apiVersion: v1
kind: Pod
metadata:
  name: kata-qemu-verify
  namespace: shadow-agents
spec:
  runtimeClassName: kata-qemu
  nodeSelector:
    remote: "true"
  tolerations:
  - key: remote.shadow.ai/dedicated
    operator: Equal
    value: "true"
    effect: NoSchedule
  containers:
  - name: test
    image: alpine:latest
    command: ["sleep", "300"]
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  restartPolicy: Never