apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: firecracker-runtime
  namespace: shadow-agents
  labels:
    app: firecracker-runtime
    component: vm-hypervisor
spec:
  selector:
    matchLabels:
      app: firecracker-runtime
  template:
    metadata:
      labels:
        app: firecracker-runtime
        component: vm-hypervisor
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
      - key: firecracker.shadow.ai/dedicated
        operator: Equal
        value: "true"
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
      - key: node.kubernetes.io/not-ready
        operator: Exists
      - key: node.kubernetes.io/unreachable
        operator: Exists
      nodeSelector:
        firecracker: "true"
      containers:
      - name: firecracker-runtime
        image: amazonlinux:2
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        volumeMounts:
        - name: dev-kvm
          mountPath: /dev/kvm
        - name: sys-fs-cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true
        - name: var-lib-firecracker
          mountPath: /var/lib/firecracker
        - name: firecracker-binary
          mountPath: /usr/local/bin/firecracker
          subPath: firecracker
        - name: jailer-binary
          mountPath: /usr/local/bin/jailer
          subPath: jailer
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command:
        - /bin/bash
        - -c
        - |
          # Install Firecracker and Jailer binaries
          yum update -y
          yum install -y wget tar
          
          # Download Firecracker binaries if not present
          if [ ! -f /usr/local/bin/firecracker ]; then
            echo "Downloading Firecracker binaries..."
            cd /tmp
            wget -O firecracker.tgz https://github.com/firecracker-microvm/firecracker/releases/download/v1.4.1/firecracker-v1.4.1-x86_64.tgz
            tar -xzf firecracker.tgz
            cp release-v1.4.1-x86_64/firecracker-v1.4.1-x86_64 /usr/local/bin/firecracker
            cp release-v1.4.1-x86_64/jailer-v1.4.1-x86_64 /usr/local/bin/jailer
            chmod +x /usr/local/bin/firecracker /usr/local/bin/jailer
            echo "Firecracker binaries installed"
          fi
          
          # Verify KVM device access
          if [ ! -c /dev/kvm ]; then
            echo "ERROR: /dev/kvm device not found. Ensure host supports KVM virtualization."
            exit 1
          fi
          
          # Set proper permissions for KVM device
          chmod 666 /dev/kvm
          
          # Create Firecracker runtime directory
          mkdir -p /var/lib/firecracker/{vms,kernels,rootfs}
          
          # Start monitoring loop
          echo "Firecracker runtime ready on node $NODE_NAME"
          while true; do
            # Monitor Firecracker processes and cleanup if needed
            ps aux | grep firecracker | grep -v grep || true
            sleep 60
          done
      volumes:
      - name: dev-kvm
        hostPath:
          path: /dev/kvm
          type: CharDevice
      - name: sys-fs-cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      - name: var-lib-firecracker
        hostPath:
          path: /var/lib/firecracker
          type: DirectoryOrCreate
      - name: firecracker-binary
        hostPath:
          path: /usr/local/bin
          type: DirectoryOrCreate
      - name: jailer-binary
        hostPath:
          path: /usr/local/bin
          type: DirectoryOrCreate
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: firecracker-config
  namespace: shadow-agents
data:
  firecracker.json: |
    {
      "boot-source": {
        "kernel_image_path": "/var/lib/firecracker/kernels/vmlinux",
        "boot_args": "console=ttyS0 reboot=k panic=1 pci=off"
      },
      "drives": [
        {
          "drive_id": "rootfs",
          "path_on_host": "/var/lib/firecracker/rootfs/shadow-rootfs.ext4",
          "is_root_device": true,
          "is_read_only": false
        }
      ],
      "machine-config": {
        "vcpu_count": 1,
        "mem_size_mib": 1024,
        "ht_enabled": false
      },
      "network-interfaces": [
        {
          "iface_id": "eth0",
          "guest_mac": "AA:FC:00:00:00:01",
          "host_dev_name": "tap0"
        }
      ]
    }

---
apiVersion: v1
kind: Service
metadata:
  name: firecracker-runtime-service
  namespace: shadow-agents
  labels:
    app: firecracker-runtime
spec:
  selector:
    app: firecracker-runtime
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  type: ClusterIP